### ISSUE TITLE
Suggestion: Switch rotation variable in sprites to rotationDegrees

### ISSUE THREAD

**Issue by MidnightBloxxer** [BlueprintFramework-Team/Blueprint#3]
## Let me explain my idea a little bit further here
(more so implementation's sake?).

At the moment it seems for every instance of the Sprite class, you store rotation in _degrees_. However, rendering code needs this to be in radians, so it is converted (_twice!_) for each time the sprite is rendered. This seems unnecessary and doesn't help the already poor performance of rendering rotated sprites (I'm sure all contributors are already aware of issues with the Matrix class and how that applies to rotation performance), so it may be a good step in that way, and it may also make things easier to understand for newcomers to the framework.

My suggestion would be to setup a system with 2 variables. rotation and rotationDegrees:

You could then, whenever rotationDegrees is set, just set rotation accordingly (rotation is now in radians by the way, unless you wanna rename it to rotationRadians or smth maybe?), and vice versa. This would be done with a set function, pretty simple stuff. Therefore you could easily use the proper numbers you need that were precalculated when the rotation was changed, rather than every frame (multiple times in the current implementation may I say!).

**Comment by SrtHero278** [comment]
i think we can do better.
i dont think the expenses came from converting to radians.
i think it mainly comes from using sin and cos.
this may be remedied through what flixel did, storing the cos and sin mult only when the angle has changed.
![image](https://github.com/BlueprintFramework-Team/Blueprint/assets/93018286/8e29b6d6-9e00-43e8-9a59-6ed8a5096fcd)

**Comment by OPG-AOI** [comment]
i love you pookie
